### ISSUE TITLE
Error on SeAT Groups Users Update

### ISSUE THREAD

**Issue by Pestichen** [herpaderpaldent/seat-groups#117]
Ive got an fresh SeAT installed and working fine so far.
But when i hit the Update Groups Users Button/Command, Horizon give me this exception.

Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher

Herpaderpaldent\Seat\SeatGroups\Exceptions\MissingMainCharacterException: The group with ID 1 does not have a main character set, or related character information is missing. in /var/www/seat/vendor/herpaderpaldent/seat-groups/src/Actions/Seat/GetMainCharacterAction.php:22

Pic: https://prnt.sc/oryenw

Anyone got an Idea ? Every user got an Main-Char set.

**Comment by herpaderpaldent** [comment]
If every user got a main-char set, the character_info entry has not been set, means the character_info was not pulled from ESI. Most probably because the token was revoked prior to seat getting the info:

https://github.com/herpaderpaldent/seat-groups/blob/8be64c7b9a007d59f226862b1b2e7bba439d363a/src/Actions/Seat/GetMainCharacterAction.php#L15-L18

it should not be the superuser account which you have created following the installation guide as the one is being filtered out: https://github.com/herpaderpaldent/seat-groups/blob/8be64c7b9a007d59f226862b1b2e7bba439d363a/src/Jobs/GroupDispatcher.php#L29 

Resolution: No seat-groups issue, problem lies within your system

**Comment by Pestichen** [comment]
It was the admin Account. Ive gave him id of Corp CEO and it seemed to work now.
Thanks!
