### ISSUE TITLE
Scheduled Jobs not running

### ISSUE THREAD

**Issue by Cwittofur** [herpaderpaldent/seat-groups#125]
I have installed Seat-Groups and I have a few groups setup, I've noticed that I need to manually go to the about tab and press the "SeAT Groups Users Update" button in order to have users placed into appropriate groups. 

I have scheduled tasks to do this automatically, however I'm not receiving any updates. I'm not sure if I set up something incorrectly.

![image](https://user-images.githubusercontent.com/13065604/75044828-4356b080-5490-11ea-97b3-ab358b5674d5.png)

![image](https://user-images.githubusercontent.com/13065604/75044881-58334400-5490-11ea-905b-c508af3075fd.png)

If there's more information needed please let me know.

**Comment by herpaderpaldent** [comment]
Wild guess, your workers are not running. Check the Horizon Dashboard and check the status. If contrairy to my guess horizon is running, check the error section and see for any seat-groups error

**Comment by Cwittofur** [comment]
I had an error, but it was only when I manually run the group update. I have deleted the user triggering the error. There were no errors during the time when the job would normally run.

My workers are running also

**Comment by herpaderpaldent** [comment]
You setup the schedule to only run every hrs so that might be a reason. If not check with core as the cain does simply the same as the button you press. If the button works the job works. 
![Screenshot_20200221-163521_Chrome](https://user-images.githubusercontent.com/6583519/75048205-6ef58d00-54c8-11ea-8c41-bd4c95d9a7dd.jpg)
