### ISSUE TITLE
Users don't get role if refresh token is missing from one of their characters

### ISSUE THREAD

**Issue by lk77** [herpaderpaldent/seat-groups#128]
Hello,

currently, if one character in a group miss a refresh token, the user gets no role at all

it's look like it's in the file CatchMissingRefreshTokenAction.php :

```
 if($this->has_missing_refresh_token) {
            SeatGroup::all()->each(function ($seatgroup) {

                // If group is member and no longer qualified
                if (! $seatgroup->isQualified($this->group) && $seatgroup->isMember($this->group)) {

                    // remove member status
                    $seatgroup->member()->detach($this->group->id);
                }

                // if group is member and still qualified
                if ($seatgroup->isQualified($this->group) && $seatgroup->isMember($this->group)) {

                    // add role id's to roles_to_temporary_remove
                    $seatgroup->role->each(function ($role) {
                        $this->roles_to_temporary_remove->push($role->id);
                    });
                }

            });
```

i don't understand why role gets removed, the only way to fix this is to disable characters when they miss tokens.

thanks.

**Comment by Crypta-Eve** [comment]
This is by design and intentional. I believe the original intent goes something like this, why should a person who is hiding information be allowed into critical services which are likely governed by role access administered by this plugin.

Take the following example;
```
Bob has three characters A, B and C. Bob is a spy but gets into your corp. 
Bob applies for roles on seat and gets them as all characters are in corp. 
Bob then invalidates tokens on character C and begins using it to send valuable intel, 
assets and isk out of the corporation. 

You will not see this as character C has an invalid token. You are blind. 
```
Further to that, tokens do not invalidate themselves, on an active seat instance there are only a handful of ways a token should become invalid;
- The user changes their password
- The user manually invalidates the token
- The character is sold and moved to another account

**Comment by herpaderpaldent** [comment]
Thank you @Crypta-Eve this sums it up and explains it very well.

**Comment by lk77** [comment]
Hello,

on our seat, everyone lost their refresh token, due to a database rollback, and everyone lost their roles too, and their discord access which is bad.

This should be a setting of the role, like a checkbox 'remove role if at least one character has an invalid refresh token'.

it's clearly a dangerous behaviour that should be choosen by the user.

**Comment by herpaderpaldent** [comment]
You are free to fork the project and implement to your convienience.

If i were you, i'd ask the members to rejoin seat to provide a fresh refresh_token. This will fix the roles again. 

Other then that: Your issue clearly arises from your missing db backup. Make sure to have your and at least your refresh tokens backed up before you manipulate your productive environment.

**Comment by lk77** [comment]
i had refresh token backed up in the db, but they have expired during the downtime.

And clearly forking is not a viable solution.

**Comment by Crypta-Eve** [comment]
A refresh token doesn't expire with downtime..... It takes 3 months of inactivity for a refresh token to expire. So unless your backup was 3 months old... There is some other cause. 

As to forking not being a viable solution... Why not? You want a change made, you need to put in some effort or wait for someone else to do so. As seat 4.0 is just around the corner I highly doubt many will work on this.

**Comment by lk77** [comment]
the backup was 8 hours old, i didn't expect the refresh token to be invalidated, i don't know what happened, perhaps it was a false positive, i don't know.

forking is not a viable solution, because it's a lot of work to maintain a fork correctly, apply upstream changes and so on. It's not worth for a small change like that.

**Comment by Crypta-Eve** [comment]
Ok.... So in summary, you don't like part of the functionality of the plugin.. Thats 100% fine, no one is forcing you to use it

You asked if a change could be made to which you were told to make a fork if you wanted that. You didnt like this because you think it is a lot of work. Thats fine, but you clearly havent looked too hard.... 

> because it's a lot of work to maintain a fork correctly, apply upstream changes

The last commit to master was Jun 9 2019.... nearly a year ago. 

Either way this will with time become a moot point as the functionality of this plugin is built into seat 4.

The fact of the matter is that this is an open source project. Herp doesnt get paid to work on it, he made it because it filled a need that he had. The fact that it does not fulfill the requirements of every single user is not a question but a guarantee. There is no obligation of anyone to make changes to try and achieve that at all. As a user with a problem, you have done the right thing and asked a question. But dont push it. You are not entitled to force a change. The plugin is MIT Licensed which is very permissive, so should you want a change that is fine, go for it. After you have made your change you can either maintain your fork (low effort for this, trust me) or you could ask what it would take to have a PR accepted. (IMO [I am not Herp though and he has his own opinions] it would need to be able to be configured, and be kept strict by default)

**Comment by lk77** [comment]
I never said i don't like it, i can understand why it was done in the first place.

And i never asked anything, just saying that this should be an option, from my point of view. 

And honestly the argument of 'no one is forcing you to use it' is irrelevant, we are not going anywhere with that kind of thought.
And by the way, i'm not using it, my corp does, so...
I was not even knowing what seat was weeks ago, my corp asked for help since there was some issues and i responded,
i didn't make the choice to use seat / seat-groups in the first place.

i know it's an open source project, i never criticized any one of you. I don't get paid either, it's not the point. And i don't push anything, just merely saying my opinion about that. If you don't make a change that's fine, i will just keep it as it is and i will not make a fork, for sure. 

I don't make forks, it's never worth it, way better making pr if possible and stick with the main repo.
